### ISSUE TITLE
compile error: missing ../include/external_calls.h

### ISSUE THREAD

**Issue by chincheta0815** [philippe44/libraop#29]
Hej,

when compiling I get an error message that ../include/external_calls.h in rtsp.c line 27 is not found.
Where can I find that/get that from?

**Comment by philippe44** [comment]
This is just shim code from the crypto module just below for memory utils: curve25519. That file should be found there. But I think you can scratch that include, it's only needed (IMHO) for the curv25519 internals.

**Comment by philippe44** [comment]
I've released a version that totally update the build system. It is only Windows and Linux for now, but this works for you, you can give it a try and hopefully if will be (at some point...) a much smoother build experience.

Basically, it's now using sub-modules instead of handcrafted solutions and there are VS projects for Windows folks. You have two options to get the source and build.

1- clone everything recursively `git clone https://github.com/philippe44/raoptools [<directory>] --recursive`. This will take everything but it's a bit download because all openssl comes with it

2- simple clone `git clone https://github.com/philippe44/raoptools [<directory>]` and then go to <directory> and do `git submodule update --init`. This will only download the "first layer" of submodule that contains only the binaries and will be **much** faster

Then, you can either simply do a 'make' and it will build for you platform, or you can use the 'build.sh' script to do cross-builds.

**Comment by tva2000hn** [comment]
> I've released a version that totally update the build system. It is only Windows and Linux for now, but this works for you, you can give it a try and hopefully if will be (at some point...) a much smoother build experience.
> 
> Basically, it's now using sub-modules instead of handcrafted solutions and there are VS projects for Windows folks. You have two options to get the source and build.
> 
> 1- clone everything recursively `git clone https://github.com/philippe44/raoptools [<directory>] --recursive`. This will take everything but it's a bit download because all openssl comes with it
> 
> 2- simple clone `git clone https://github.com/philippe44/raoptools [<directory>]` and then go to and do `git submodule update --init`. This will only download the "first layer" of submodule that contains only the binaries and will be **much** faster
> 
> Then, you can either simply do a 'make' and it will build for you platform, or you can use the 'build.sh' script to do cross-builds.

Tried to do the first way but it seems ```libraop.vcxproj``` is missing. I'd love to add AirPlay2 support to this library.

**Comment by philippe44** [comment]
Indeed - I've added it back
